name: 'change zip name'
on:
  issues:
    types:
      - opened

author: 'Andrew wognaroski'
description: 'change zip name to make it works with plugin'
jobs:
  build:
   runs-on: ubuntu-latest
      steps:
        with:
          type: 'zip'
          directory: 'prestashop-master'

name: Upload Release
with:
  artifacts: 'paylands'
  token: